// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: sso.proto

// to be honest, this is a user system, not only a SSO
// but for the historical reason, the project name is sso

package sso

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_INTERN    Role = 0
	Role_REGULAR   Role = 1
	Role_GRADUATED Role = 2
	Role_LEADER    Role = 3
	Role_DEVOPS    Role = 4
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "INTERN",
		1: "REGULAR",
		2: "GRADUATED",
		3: "LEADER",
		4: "DEVOPS",
	}
	Role_value = map[string]int32{
		"INTERN":    0,
		"REGULAR":   1,
		"GRADUATED": 2,
		"LEADER":    3,
		"DEVOPS":    4,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_sso_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_sso_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{0}
}

type Group int32

const (
	Group_invalidGroup Group = 0 // for gorm, 0 is invalid when update
	Group_WEB          Group = 1
	Group_LAB          Group = 2
	Group_PM           Group = 3
	Group_DESIGN       Group = 4
	Group_ANDROID      Group = 5
	Group_IOS          Group = 6
	Group_GAME         Group = 7
	Group_AI           Group = 8
)

// Enum value maps for Group.
var (
	Group_name = map[int32]string{
		0: "invalidGroup",
		1: "WEB",
		2: "LAB",
		3: "PM",
		4: "DESIGN",
		5: "ANDROID",
		6: "IOS",
		7: "GAME",
		8: "AI",
	}
	Group_value = map[string]int32{
		"invalidGroup": 0,
		"WEB":          1,
		"LAB":          2,
		"PM":           3,
		"DESIGN":       4,
		"ANDROID":      5,
		"IOS":          6,
		"GAME":         7,
		"AI":           8,
	}
)

func (x Group) Enum() *Group {
	p := new(Group)
	*p = x
	return p
}

func (x Group) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Group) Descriptor() protoreflect.EnumDescriptor {
	return file_sso_proto_enumTypes[1].Descriptor()
}

func (Group) Type() protoreflect.EnumType {
	return &file_sso_proto_enumTypes[1]
}

func (x Group) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Group.Descriptor instead.
func (Group) EnumDescriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{1}
}

type Gender int32

const (
	Gender_invalidGender Gender = 0
	Gender_MALE          Gender = 1
	Gender_FEMALE        Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "invalidGender",
		1: "MALE",
		2: "FEMALE",
	}
	Gender_value = map[string]int32{
		"invalidGender": 0,
		"MALE":          1,
		"FEMALE":        2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_sso_proto_enumTypes[2].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_sso_proto_enumTypes[2]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{2}
}

type Action int32

const (
	Action_invalidAction Action = 0
	Action_READ          Action = 1
	Action_FULL          Action = 2
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "invalidAction",
		1: "READ",
		2: "FULL",
	}
	Action_value = map[string]int32{
		"invalidAction": 0,
		"READ":          1,
		"FULL":          2,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_sso_proto_enumTypes[3].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_sso_proto_enumTypes[3]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{3}
}

type ExternalType int32

const (
	ExternalType_invalidEType ExternalType = 0
	ExternalType_All          ExternalType = 1
	ExternalType_LARK         ExternalType = 2
	ExternalType_QQ           ExternalType = 3
)

// Enum value maps for ExternalType.
var (
	ExternalType_name = map[int32]string{
		0: "invalidEType",
		1: "All",
		2: "LARK",
		3: "QQ",
	}
	ExternalType_value = map[string]int32{
		"invalidEType": 0,
		"All":          1,
		"LARK":         2,
		"QQ":           3,
	}
)

func (x ExternalType) Enum() *ExternalType {
	p := new(ExternalType)
	*p = x
	return p
}

func (x ExternalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExternalType) Descriptor() protoreflect.EnumDescriptor {
	return file_sso_proto_enumTypes[4].Descriptor()
}

func (ExternalType) Type() protoreflect.EnumType {
	return &file_sso_proto_enumTypes[4]
}

func (x ExternalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExternalType.Descriptor instead.
func (ExternalType) EnumDescriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{4}
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"uid" gorm:"column:uid;primaryKey"
	UID string `protobuf:"bytes,1,opt,name=UID,proto3" json:"uid" gorm:"column:uid;primaryKey"`
	// @gotags: json:"group" gorm:"-"
	Group []Group `protobuf:"varint,2,rep,packed,name=Group,proto3,enum=sso.Group" json:"group" gorm:"-"`
	// @gotags: json:"role" gorm:"column:role"
	Role Role `protobuf:"varint,3,opt,name=Role,proto3,enum=sso.Role" json:"role" gorm:"column:role"`
	// external application, like lark info
	// @gotags: json:"external_infos" gorm:"-"
	ExternalInfos []*ExternalInfo `protobuf:"bytes,4,rep,name=ExternalInfos,proto3" json:"external_infos" gorm:"-"`
	// @gotags: json:"name" gorm:"column:name"
	Name string `protobuf:"bytes,5,opt,name=Name,proto3" json:"name" gorm:"column:name"`
	// @gotags: json:"phone" gorm:"column:phone"
	Phone string `protobuf:"bytes,6,opt,name=Phone,proto3" json:"phone" gorm:"column:phone"`
	// @gotags: json:"email" gorm:"column:email"
	Email string `protobuf:"bytes,7,opt,name=Email,proto3" json:"email" gorm:"column:email"`
	// @gotags: json:"password" gorm:"column:password"
	Password string `protobuf:"bytes,8,opt,name=Password,proto3" json:"password" gorm:"column:password"`
	// @gotags: json:"totp_secret" gorm:"column:totp_secret"
	TOTPSecret string `protobuf:"bytes,9,opt,name=TOTPSecret,proto3" json:"totp_secret" gorm:"column:totp_secret"`
	// @gotags: json:"avatar_url" gorm:"column:avatar_url"
	AvatarURL string `protobuf:"bytes,10,opt,name=AvatarURL,proto3" json:"avatar_url" gorm:"column:avatar_url"`
	// @gotags: json:"gender" gorm:"column:gender"
	Gender Gender `protobuf:"varint,12,opt,name=Gender,proto3,enum=sso.Gender" json:"gender" gorm:"column:gender"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sso_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUID() string {
	if x != nil {
		return x.UID
	}
	return ""
}

func (x *User) GetGroup() []Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *User) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_INTERN
}

func (x *User) GetExternalInfos() []*ExternalInfo {
	if x != nil {
		return x.ExternalInfos
	}
	return nil
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetTOTPSecret() string {
	if x != nil {
		return x.TOTPSecret
	}
	return ""
}

func (x *User) GetAvatarURL() string {
	if x != nil {
		return x.AvatarURL
	}
	return ""
}

func (x *User) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_invalidGender
}

type Permission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"action" gorm:"column:action"
	Action Action `protobuf:"varint,1,opt,name=Action,proto3,enum=sso.Action" json:"action" gorm:"column:action"`
	// @gotags: json:"resource" gorm:"column:resource"
	Resource string `protobuf:"bytes,2,opt,name=Resource,proto3" json:"resource" gorm:"column:resource"` // the resouce is defined by URL
}

func (x *Permission) Reset() {
	*x = Permission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sso_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{1}
}

func (x *Permission) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_invalidAction
}

func (x *Permission) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type ExternalInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"ename" gorm:"column:ename"
	EName ExternalType `protobuf:"varint,1,opt,name=EName,proto3,enum=sso.ExternalType" json:"ename" gorm:"column:ename"`
	// @gotags: json:"eid" gorm:"eid"
	EID string `protobuf:"bytes,2,opt,name=EID,proto3" json:"eid" gorm:"eid"`
	// @gotags: json:"detail" gorm:"-"
	Detail *anypb.Any `protobuf:"bytes,3,opt,name=Detail,proto3" json:"detail" gorm:"-"`
}

func (x *ExternalInfo) Reset() {
	*x = ExternalInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sso_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExternalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalInfo) ProtoMessage() {}

func (x *ExternalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalInfo.ProtoReflect.Descriptor instead.
func (*ExternalInfo) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{2}
}

func (x *ExternalInfo) GetEName() ExternalType {
	if x != nil {
		return x.EName
	}
	return ExternalType_invalidEType
}

func (x *ExternalInfo) GetEID() string {
	if x != nil {
		return x.EID
	}
	return ""
}

func (x *ExternalInfo) GetDetail() *anypb.Any {
	if x != nil {
		return x.Detail
	}
	return nil
}

type QueryAccessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID     string      `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Permission *Permission `protobuf:"bytes,2,opt,name=Permission,proto3" json:"Permission,omitempty"`
}

func (x *QueryAccessRequest) Reset() {
	*x = QueryAccessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sso_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAccessRequest) ProtoMessage() {}

func (x *QueryAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAccessRequest.ProtoReflect.Descriptor instead.
func (*QueryAccessRequest) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{3}
}

func (x *QueryAccessRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *QueryAccessRequest) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type QueryAccessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HaveAccess bool `protobuf:"varint,1,opt,name=HaveAccess,proto3" json:"HaveAccess,omitempty"`
}

func (x *QueryAccessResponse) Reset() {
	*x = QueryAccessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sso_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAccessResponse) ProtoMessage() {}

func (x *QueryAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAccessResponse.ProtoReflect.Descriptor instead.
func (*QueryAccessResponse) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{4}
}

func (x *QueryAccessResponse) GetHaveAccess() bool {
	if x != nil {
		return x.HaveAccess
	}
	return false
}

type QueryUserInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *QueryUserInfoRequest) Reset() {
	*x = QueryUserInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sso_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserInfoRequest) ProtoMessage() {}

func (x *QueryUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserInfoRequest.ProtoReflect.Descriptor instead.
func (*QueryUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{5}
}

func (x *QueryUserInfoRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type OperateExternalInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID       string        `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	ExternalInfo *ExternalInfo `protobuf:"bytes,2,opt,name=ExternalInfo,proto3" json:"ExternalInfo,omitempty"`
}

func (x *OperateExternalInfoRequest) Reset() {
	*x = OperateExternalInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sso_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperateExternalInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateExternalInfoRequest) ProtoMessage() {}

func (x *OperateExternalInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateExternalInfoRequest.ProtoReflect.Descriptor instead.
func (*OperateExternalInfoRequest) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{6}
}

func (x *OperateExternalInfoRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *OperateExternalInfoRequest) GetExternalInfo() *ExternalInfo {
	if x != nil {
		return x.ExternalInfo
	}
	return nil
}

type StandardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *StandardResponse) Reset() {
	*x = StandardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sso_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StandardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardResponse) ProtoMessage() {}

func (x *StandardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardResponse.ProtoReflect.Descriptor instead.
func (*StandardResponse) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{7}
}

func (x *StandardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StandardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type KickUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExternalType ExternalType `protobuf:"varint,1,opt,name=ExternalType,proto3,enum=sso.ExternalType" json:"ExternalType,omitempty"`
	UserId       string       `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	GroupId      string       `protobuf:"bytes,3,opt,name=GroupId,proto3" json:"GroupId,omitempty"`
}

func (x *KickUserRequest) Reset() {
	*x = KickUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sso_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserRequest) ProtoMessage() {}

func (x *KickUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserRequest.ProtoReflect.Descriptor instead.
func (*KickUserRequest) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{8}
}

func (x *KickUserRequest) GetExternalType() ExternalType {
	if x != nil {
		return x.ExternalType
	}
	return ExternalType_invalidEType
}

func (x *KickUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *KickUserRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type OperatePermissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID     string      `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Permission *Permission `protobuf:"bytes,2,opt,name=Permission,proto3" json:"Permission,omitempty"`
}

func (x *OperatePermissionRequest) Reset() {
	*x = OperatePermissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sso_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatePermissionRequest) ProtoMessage() {}

func (x *OperatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatePermissionRequest.ProtoReflect.Descriptor instead.
func (*OperatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{9}
}

func (x *OperatePermissionRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *OperatePermissionRequest) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

var File_sso_proto protoreflect.FileDescriptor

var file_sso_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x73, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x73, 0x73, 0x6f,
	0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd1, 0x02, 0x0a, 0x04,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x55, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x73, 0x73, 0x6f, 0x2e, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1d, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x73, 0x73, 0x6f, 0x2e, 0x52, 0x6f, 0x6c,
	0x65, 0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x37, 0x0a, 0x0d, 0x45, 0x78, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x73, 0x73, 0x6f, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x0d, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x54, 0x4f, 0x54, 0x50, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x54, 0x4f, 0x54, 0x50, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x52, 0x4c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x52, 0x4c, 0x12, 0x23, 0x0a, 0x06, 0x47, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x73, 0x73, 0x6f,
	0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22,
	0x4d, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a,
	0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e,
	0x73, 0x73, 0x6f, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x77,
	0x0a, 0x0c, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x27,
	0x0a, 0x05, 0x45, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e,
	0x73, 0x73, 0x6f, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x05, 0x45, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x45, 0x49, 0x44, 0x12, 0x2c, 0x0a, 0x06, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52,
	0x06, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x5d, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x2f, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x73, 0x6f, 0x2e,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x35, 0x0a, 0x13, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x48, 0x61, 0x76, 0x65, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0a, 0x48, 0x61, 0x76, 0x65, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x2e, 0x0a,
	0x14, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x6b, 0x0a,
	0x1a, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x35, 0x0a, 0x0c, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x73, 0x6f, 0x2e,
	0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x45, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x46, 0x0a, 0x10, 0x53, 0x74,
	0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x7a, 0x0a, 0x0f, 0x4b, 0x69, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0c, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x73, 0x73,
	0x6f, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c,
	0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x63,
	0x0a, 0x18, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x2f, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x73, 0x6f, 0x2e, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x2a, 0x46, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x49,
	0x4e, 0x54, 0x45, 0x52, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x47, 0x55, 0x4c,
	0x41, 0x52, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x47, 0x52, 0x41, 0x44, 0x55, 0x41, 0x54, 0x45,
	0x44, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x45, 0x41, 0x44, 0x45, 0x52, 0x10, 0x03, 0x12,
	0x0a, 0x0a, 0x06, 0x44, 0x45, 0x56, 0x4f, 0x50, 0x53, 0x10, 0x04, 0x2a, 0x67, 0x0a, 0x05, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x12, 0x10, 0x0a, 0x0c, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x57, 0x45, 0x42, 0x10, 0x01, 0x12,
	0x07, 0x0a, 0x03, 0x4c, 0x41, 0x42, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02, 0x50, 0x4d, 0x10, 0x03,
	0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x53, 0x49, 0x47, 0x4e, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07,
	0x41, 0x4e, 0x44, 0x52, 0x4f, 0x49, 0x44, 0x10, 0x05, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4f, 0x53,
	0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x41, 0x4d, 0x45, 0x10, 0x07, 0x12, 0x06, 0x0a, 0x02,
	0x41, 0x49, 0x10, 0x08, 0x2a, 0x31, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x11,
	0x0a, 0x0d, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46,
	0x45, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x02, 0x2a, 0x2f, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x11, 0x0a, 0x0d, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x45, 0x41, 0x44, 0x10, 0x01, 0x12, 0x08,
	0x0a, 0x04, 0x46, 0x55, 0x4c, 0x4c, 0x10, 0x02, 0x2a, 0x3b, 0x0a, 0x0c, 0x45, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x69, 0x6e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x45, 0x54, 0x79, 0x70, 0x65, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x6c,
	0x6c, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x41, 0x52, 0x4b, 0x10, 0x02, 0x12, 0x06, 0x0a,
	0x02, 0x51, 0x51, 0x10, 0x03, 0x32, 0x91, 0x01, 0x0a, 0x0a, 0x53, 0x53, 0x4f, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42,
	0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x2e, 0x73, 0x73, 0x6f, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x73, 0x73, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x12, 0x49,
	0x0a, 0x0f, 0x41, 0x64, 0x64, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x1f, 0x2e, 0x73, 0x73, 0x6f, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x45,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x73, 0x73, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x53, 0x74,
	0x75, 0x64, 0x69, 0x6f, 0x2f, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x53, 0x53, 0x4f, 0x2f, 0x70,
	0x62, 0x2f, 0x73, 0x73, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sso_proto_rawDescOnce sync.Once
	file_sso_proto_rawDescData = file_sso_proto_rawDesc
)

func file_sso_proto_rawDescGZIP() []byte {
	file_sso_proto_rawDescOnce.Do(func() {
		file_sso_proto_rawDescData = protoimpl.X.CompressGZIP(file_sso_proto_rawDescData)
	})
	return file_sso_proto_rawDescData
}

var file_sso_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_sso_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_sso_proto_goTypes = []interface{}{
	(Role)(0),                          // 0: sso.Role
	(Group)(0),                         // 1: sso.Group
	(Gender)(0),                        // 2: sso.Gender
	(Action)(0),                        // 3: sso.Action
	(ExternalType)(0),                  // 4: sso.ExternalType
	(*User)(nil),                       // 5: sso.User
	(*Permission)(nil),                 // 6: sso.Permission
	(*ExternalInfo)(nil),               // 7: sso.ExternalInfo
	(*QueryAccessRequest)(nil),         // 8: sso.QueryAccessRequest
	(*QueryAccessResponse)(nil),        // 9: sso.QueryAccessResponse
	(*QueryUserInfoRequest)(nil),       // 10: sso.QueryUserInfoRequest
	(*OperateExternalInfoRequest)(nil), // 11: sso.OperateExternalInfoRequest
	(*StandardResponse)(nil),           // 12: sso.StandardResponse
	(*KickUserRequest)(nil),            // 13: sso.KickUserRequest
	(*OperatePermissionRequest)(nil),   // 14: sso.OperatePermissionRequest
	(*anypb.Any)(nil),                  // 15: google.protobuf.Any
}
var file_sso_proto_depIdxs = []int32{
	1,  // 0: sso.User.Group:type_name -> sso.Group
	0,  // 1: sso.User.Role:type_name -> sso.Role
	7,  // 2: sso.User.ExternalInfos:type_name -> sso.ExternalInfo
	2,  // 3: sso.User.Gender:type_name -> sso.Gender
	3,  // 4: sso.Permission.Action:type_name -> sso.Action
	4,  // 5: sso.ExternalInfo.EName:type_name -> sso.ExternalType
	15, // 6: sso.ExternalInfo.Detail:type_name -> google.protobuf.Any
	6,  // 7: sso.QueryAccessRequest.Permission:type_name -> sso.Permission
	7,  // 8: sso.OperateExternalInfoRequest.ExternalInfo:type_name -> sso.ExternalInfo
	4,  // 9: sso.KickUserRequest.ExternalType:type_name -> sso.ExternalType
	6,  // 10: sso.OperatePermissionRequest.Permission:type_name -> sso.Permission
	10, // 11: sso.SSOService.GetUserBasicInfo:input_type -> sso.QueryUserInfoRequest
	11, // 12: sso.SSOService.AddExternalInfo:input_type -> sso.OperateExternalInfoRequest
	5,  // 13: sso.SSOService.GetUserBasicInfo:output_type -> sso.User
	12, // 14: sso.SSOService.AddExternalInfo:output_type -> sso.StandardResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_sso_proto_init() }
func file_sso_proto_init() {
	if File_sso_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sso_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sso_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Permission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sso_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExternalInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sso_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryAccessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sso_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryAccessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sso_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryUserInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sso_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperateExternalInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sso_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StandardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sso_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sso_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperatePermissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sso_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sso_proto_goTypes,
		DependencyIndexes: file_sso_proto_depIdxs,
		EnumInfos:         file_sso_proto_enumTypes,
		MessageInfos:      file_sso_proto_msgTypes,
	}.Build()
	File_sso_proto = out.File
	file_sso_proto_rawDesc = nil
	file_sso_proto_goTypes = nil
	file_sso_proto_depIdxs = nil
}
