kind: pipeline
type: docker
name: SSO-CI

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone --depth=1 -b $DRONE_COMMIT_BRANCH https://github.com.cnpmjs.org/UniqueStudio/UniqueSSO.git .

  - name: build_publish
    image: plugins/docker
    depends_on:
      - clone
    settings:
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      tags: ${DRONE_TAG=latest}
      context: ./SSO
      dockerfile: ./SSO/Dockerfile
      build_args:
        - GOMODCACHEDIR=/drone/src/go
      registry: ccr.ccs.tencentyun.com
      repo: ccr.ccs.tencentyun.com/unique-studio/sso
    volumes:
      - name: sock
        path: /var/run/docker.sock
      - name: local
        path: /var/lib/docker
      - name: go-pkg
        path: /drone/src/go

  - name: deploy_dev
    image: docker/compose:1.29.2
    commands:
      - docker-compose up -d --remove-orphans uniquesso-back
    depends_on:
      - build_publish
    volumes:
      - name: sock
        path: /var/run/docker.sock
    when:
      branch:
        - dev
      event:
        - push
  - name: deploy_prod
    image: docker/compose:1.29.2
    commands:
      - docker-compose up -d --remove-orphans uniquesso-back
    depends_on:
      - build_publish
    volumes:
      - name: sock
        path: /var/run/docker.sock
    when:
      event:
        - tag

volumes:
  - name: sock
    host:
      path: /var/run/docker.sock
  - name: local
    host:
      path: /var/lib/docker
  - name: go-pkg
    host:
      path: /root/go

trigger:
  branch:
    - dev
  event:
    - push
    - tag
