version: "3.9"

x-logging: &loki-logging
    driver: loki
    options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-external-labels: job=dockerlogs,maintainer=xylonx,environment=development
        loki-pipeline-stages: |
            - json:
                expressions:
                    traceId: TraceID
                    spanId: SpanID
                    level: level
            - labels:
                traceId:
                spanId:
                level:

services:
    uniquesso-back:
        image: ccr.ccs.tencentyun.com/unique-studio/sso:${DRONE_TAG:-latest}
        container_name: dev-sso-back
        restart: always
        volumes:
            - /root/service-dev/SSO/conf.yaml:/opt/uniquesso-backend/settings.yaml
        ports:
            - 6004:5000
        networks:
            - uniquesso
            - db_network
            - apm
        logging: *loki-logging
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.grafana.rule=Host(`dev.sso.hustunique.com`)"

networks:
    uniquesso:
        internal: true
        name: uniques
    db_network:
        external: true
        name: database
    apm: 
        external: true
        name: apm